frr version 8.5
frr defaults traditional
hostname evpn-bastion-A
log syslog informational
service integrated-vtysh-config
!
router bgp 65000
 bgp router-id 10.254.254.1
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 bgp listen limit 32
 neighbor OCP peer-group
 neighbor OCP remote-as 65001
 bgp listen range 10.10.10.0/24 peer-group OCP
 neighbor 10.254.254.2 remote-as 65000
 neighbor 10.254.254.2 update-source 10.254.254.1
 neighbor OCP attribute-unchanged next-hop
 neighbor OCP send-community both
 neighbor 10.254.254.2 send-community both
 !
 address-family l2vpn evpn
  neighbor OCP activate
  neighbor 10.254.254.2 activate
 exit-address-family
!
line vty
!
