apiVersion: k8s.ovn.org/v1
kind: RouteAdvertisements
metadata:
  name: sydney-l2-evpn
spec:
  targetVRF: auto
  advertisements:
    - PodNetwork
  nodeSelector: {}
  frrConfigurationSelector:
    matchLabels:
      evpn-demo: sydney-l2
  networkSelectors:
    - networkSelectionType: ClusterUserDefinedNetworks
      clusterUserDefinedNetworkSelector:
        networkSelector:
          matchLabels:
            evpn-demo: sydney-l2
