#!/usr/bin/env bash
# Log in to both OpenShift clusters and remember the resulting oc contexts.
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.site-contexts.env"

if ! command -v oc >/dev/null 2>&1; then
  echo 'ERROR: oc is not installed or is not on PATH.' >&2
  exit 1
fi

ask_api_url() {
  local site_name="$1" configured_url="$2" url
  if [[ -n "$configured_url" ]]; then
    url="$configured_url"
  else
    read -r -p "$site_name API URL (for example https://api.example.com:6443): " url
  fi
  if [[ ! "$url" =~ ^https://[^[:space:]]+$ ]]; then
    echo "ERROR: $site_name API URL must start with https:// and contain no whitespace." >&2
    return 1
  fi
  printf '%s\n' "$url"
}

login_and_capture() {
  local site_name="$1" api_url="$2" ctx server
  printf '\n=== Log in to %s ===\n' "$site_name" >&2
  # Let oc prompt for credentials or a token. Never request tokens through
  # this script, print them, or save them in the context environment file.
  oc login "$api_url" >&2
  ctx="$(oc config current-context)"
  server="$(oc config view --minify -o jsonpath='{.clusters[0].cluster.server}')"
  if [[ -z "$ctx" || -z "$server" ]]; then
    echo "ERROR: Cannot identify the active oc context for $site_name." >&2
    return 1
  fi
  printf '%s\t%s\n' "$ctx" "$server"
}

SITE_A_API="$(ask_api_url 'Site A (site-a-sydney-cluster-kcp74)' "${SITE_A_API_URL:-}")"
SITE_A_CAPTURE="$(login_and_capture 'Site A' "$SITE_A_API")"
IFS=$'\t' read -r CAPTURED_A_CONTEXT CAPTURED_A_SERVER <<< "$SITE_A_CAPTURE"

SITE_B_API="$(ask_api_url 'Site B (site-b-sydney-cluster-9r9gz)' "${SITE_B_API_URL:-}")"
SITE_B_CAPTURE="$(login_and_capture 'Site B' "$SITE_B_API")"
IFS=$'\t' read -r CAPTURED_B_CONTEXT CAPTURED_B_SERVER <<< "$SITE_B_CAPTURE"

if [[ "$CAPTURED_A_CONTEXT" == "$CAPTURED_B_CONTEXT" || "$CAPTURED_A_SERVER" == "$CAPTURED_B_SERVER" ]]; then
  echo 'ERROR: Both logins resolved to the same context or API server.' >&2
  echo 'Check your Site A and Site B API URLs. The existing context file was not changed.' >&2
  exit 1
fi

# Write only context names; oc keeps authentication in your normal kubeconfig.
# Atomic write prevents a failed second login from overwriting working config.
umask 077
TMP_FILE="$(mktemp "$ROOT_DIR/.site-contexts.env.tmp.XXXXXX")"
trap 'rm -f -- "$TMP_FILE"' EXIT
{
  printf '# Generated by scripts/00-login.sh. No credentials are stored here.\n'
  printf 'export SITE_A_CONTEXT=%q\n' "$CAPTURED_A_CONTEXT"
  printf 'export SITE_B_CONTEXT=%q\n' "$CAPTURED_B_CONTEXT"
} > "$TMP_FILE"
mv -f -- "$TMP_FILE" "$ENV_FILE"
trap - EXIT

printf '\nSaved both contexts to %s\n' "$ENV_FILE"
printf '  Site A: %s (%s)\n' "$CAPTURED_A_CONTEXT" "$CAPTURED_A_SERVER"
printf '  Site B: %s (%s)\n' "$CAPTURED_B_CONTEXT" "$CAPTURED_B_SERVER"
printf '\nAll repo scripts now load this file automatically.\n'
printf 'To use the variables in this terminal too: source ./.site-contexts.env\n'
